"use client";
import { useState } from "react";

type Lang = "en" | "ar";

const ui = {
  en: {
    nav: [["#proof-wall","Projects"],["#approach","Approach"],["#about","About"]], available:"Open to the right opportunity", role:"Creative & Content Strategist", leadA:"Strategy behind", leadB:"content that moves.", intro:"I turn scattered content into a clear strategy, sharper ideas, and work that earns attention — then moves people to act.", work:"Explore the work", contact:"Let’s talk", proof:"Proof, matched to the problem", metrics:["Organic reach","Zero ad spend","One video"], approachK:"The approach", approachTitle:"Creative, but never random.", approachIntro:"Every piece of content gets a job before it gets a format.", steps:[["01","Find the real problem","I begin with the goal, audience, funnel stage, and the one action content needs to drive."],["02","Build the route","I turn insights into pillars, hooks, scripts, visual direction, and a clear production path."],["03","Test what works","I align the team, ship, read performance, and iterate until the result speaks."]], aboutK:"Profile", aboutTitle:"The strategist who can execute.", aboutP:"I work between strategy and the people bringing it to life — connecting content, copy, design, video, media buying, and the client around one clear direction.", abilities:["Content Strategy","Creative Ideation","Creative Direction","Performance Copy","Organic Testing","Cross-team Execution"], ctaK:"Have a content problem?", ctaTitle:"Let’s make the next move clear.", email:"Start a conversation", footer:"Abdallah Al-Mohandes — Cairo, Egypt"
  },
  ar: {
    nav: [["#proof-wall","المشاريع"],["#approach","طريقتي"],["#about","عني"]], available:"متاح للفرصة المناسبة", role:"استراتيجي إبداع ومحتوى", leadA:"استراتيجية وراء", leadB:"محتوى يصنع تأثيرًا.", intro:"أحوّل المحتوى المتفرق إلى استراتيجية واضحة، وأفكار أقوى، وتنفيذ يجذب الانتباه — ثم يدفع الناس لاتخاذ خطوة.", work:"شاهد الأعمال", contact:"تواصل معي", proof:"الدليل المناسب لكل مشكلة", metrics:["وصول طبيعي","بدون إعلانات","فيديو واحد"], approachK:"طريقة الشغل", approachTitle:"إبداع، لكن مش عشوائي.", approachIntro:"كل قطعة محتوى لازم يكون لها دور قبل ما يكون لها شكل.", steps:[["01","نحدد المشكلة الحقيقية","أبدأ بالهدف والجمهور ومرحلة الـfunnel والخطوة الواحدة المطلوبة من المحتوى."],["02","نبني الطريق","أحوّل الفهم إلى محاور وhooks وسكريبتات واتجاه بصري ومسار تنفيذ واضح."],["03","نختبر اللي بيشتغل","أوحّد الفريق، ننشر، نقرأ الأداء ونطوّر لحد ما النتيجة تتكلم."]], aboutK:"عنّي", aboutTitle:"استراتيجي يعرف ينفّذ.", aboutP:"أعمل في المساحة بين الاستراتيجية والأشخاص الذين يحولونها إلى واقع — أوحّد المحتوى والكتابة والتصميم والفيديو والميديا باينج والعميل حول اتجاه واحد واضح.", abilities:["استراتيجية المحتوى","ابتكار الأفكار","التوجيه الإبداعي","كتابة إعلانات الأداء","الاختبار الطبيعي","تنسيق الفرق"], ctaK:"عندك مشكلة في المحتوى؟", ctaTitle:"خلّينا نخلي الخطوة الجاية واضحة.", email:"ابدأ محادثة", footer:"عبدالله المهندس — القاهرة، مصر"
  }
};

const rabhaReels = [
  {id:"2252826048836354", views:"47K", image:"/rabha/reel-47k.jpg"},
  {id:"921005460270732", views:"18K", image:"/rabha/reel-18k.jpg"},
  {id:"1487970329748086", views:"13K", image:"/rabha/reel-13k.jpg"},
  {id:"1342410861035210", views:"6.4K", image:"/rabha/reel-64k.jpg"},
  {id:"1517874099958400", views:"6K", image:"/rabha/reel-6k.jpg"},
  {id:"1306608900933541", views:"3.1K", image:"/rabha/reel-31k.jpg"},
];

const mariemReels = [
  {id:"852477507840942", views:"2M", image:"/mariem/reel-2m-new.jpg", en:"Organic storytelling", ar:"سرد قصصي أورجانيك"},
  {id:"1150334803884934", views:"155K", image:"/mariem/reel-155k.jpg", en:"Paid sales creative", ar:"محتوى بيعي للإعلانات"},
  {id:"4373980182748647", views:"149K", image:"/mariem/reel-149k.jpg", en:"Offer-led ad", ar:"عرض بيعي للإعلانات"},
  {id:"2127511864456822", views:"78K", image:"/mariem/reel-78k.jpg", en:"Ad script", ar:"سكريبت إعلاني"},
  {id:"1584204506002319", views:"60K", image:"/mariem/reel-60k.jpg", en:"Comfort angle", ar:"زاوية الراحة"},
  {id:"809876478729148", views:"42K", image:"/mariem/reel-42k.jpg", en:"Learning test", ar:"تجربة للتعلّم"},
];

const proofSources = [
  { brand:"CyberScale", base:"https://www.instagram.com/cyberscale.agency/reel/", ids:["DayTxWtRnO6","DaunnBio4-I","DapbolmIP9I","DaU-099RD1V","DaI43gHx4Hw","DZzhMoHx-MU","DZmgnKsxn9W","DZfH27lxtCC","DZQIxU6RzFN"] },
  { brand:"Rabha", base:"https://www.instagram.com/rabha.factory/reel/", ids:["DcbVf8GDIKL","DcYwvHdAeWV","DcRP_TniXxq","DcOdejXCbqO","DcLYA2FlOPu","DcI7R__j45v","Dbs4jj4kbm3","DbiorfrgGCT","DbVoBMVEe2D"] },
  { brand:"Tallah Dental", base:"https://www.instagram.com/tallah.dentalclinic/reel/", ids:["DRCc2gYgNAu","DQ4q-qqjG9y","DQzVVV9jDVF","DQPaTIwjCbE","DPyUun-DKad","DO3vFeaDEXN"] },
  { brand:"First Axes", base:"https://www.instagram.com/first.axes/reel/", ids:["DYhLV5XIr8k","DYCb2TMIZDx","DXUR4SwjCsw","DXMdNdbCEAL","DXJ4y-ZgdNB","DXJdGELEm_4","DWd8eKVCBxZ","DWEuUEECCk-","DVYoid5ACfE"] },
  { brand:"EBT", base:"https://www.instagram.com/ebt.sa/reel/", ids:["CwNDF78s9f2","Cz83tbyIQ5Q","DYE-8ZxIPW9","DX_8RdnI7wi","DU0cmt5iIDu","DUbssJeCDNR","DUYSumACPu7","DUVDSCbCM7K","DUE_E3diIKz"] },
  { brand:"Khyoot", base:"https://www.instagram.com/khyoot.official/reel/", ids:["Dcbd8sQqKy4","DcWGIT1oM7F","DcRP_7wlJcw","DcOdenDIxQX","Dbi5Q_yErxc","DbQntsPAKlM","DbLeoIKmxIj","DbI_GAWjlS5","DbGSVXQgt6q"] },
  { brand:"Selected work", base:"https://www.instagram.com/reel/", ids:["DVmMc0vDO6H","DVq7_oajNWS","DWCYoBBDDz_","DWy7T-QMi0x","DWe0R-CsrPH","DWR6Mb7sDgU","DXKYMTxttJL","DXuT935DI-y","DXrk3UVMSE1"] },
];

const proofItems = Array.from(
  {length:Math.max(...proofSources.map(source => source.ids.length))},
  (_,itemIndex) => proofSources.map(source => {
    const id = source.ids[itemIndex];
    return id ? {
      image:`/proof/${id}.jpg`,
      href:`${source.base}${id}/`,
      alt:`${source.brand} reel`,
    } : null;
  }),
).flat().filter((item): item is NonNullable<typeof item> => item !== null);

const proofRows = [0,1,2].map(rowIndex => proofItems.filter((_,itemIndex) => itemIndex % 3 === rowIndex));

export default function Home(){
  const [lang,setLang]=useState<Lang>("en"); const t=ui[lang]; const rtl=lang==="ar";
  return <main className={rtl?"site rtl":"site"} dir={rtl?"rtl":"ltr"}>
    <nav className="newNav"><a href="#top" className="wordmark">HANDASA<span>®</span></a><div className="navCenter">{t.nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</div><div className="navActions"><button className="langSwitch" onClick={()=>setLang(rtl?"en":"ar")} aria-label={rtl?"Switch to English":"التبديل للعربية"}>{rtl?"EN":"ع"}</button><a className="contactPill" href="mailto:abdallamhmd273@gmail.com">{t.contact} <span>↗</span></a></div></nav>
    <div className="heroFlipStage"><section className="newHero cinematicHero" id="top"><figure className="heroBackdrop"><img src="/abdallah-hero.jpg" alt={rtl?"عبدالله المهندس أثناء العمل خلف الكاميرا":"Abdallah Al-Mohandes working behind the camera"}/></figure><div className="heroShade"/><div className="heroStatus"><span className="statusDot" />{t.available}<b>CAIRO · EGYPT</b></div><div className="heroIdentity"><p>{t.role}</p><h1><span>{rtl?"عبدالله":"ABDALLAH"}</span><strong>{rtl?"المهندس":"AL-MOHANDES"}</strong></h1><div><p>{t.intro}</p><a href="#proof-wall">{rtl?"اكتشف الشغل":"DISCOVER THE WORK"}<span>↓</span></a></div></div><div className="heroScroll"><span>01</span><p>{rtl?"انزل لتشوف حجم الشغل":"SCROLL TO SEE THE WORK"}</p></div></section></div>
    <section className="proofWall" id="proof-wall"><div className="proofWallHead" dir={rtl?"rtl":"ltr"}><small>02 / {rtl?"حجم الشغل":"THE PROOF WALL"}</small><h2>{rtl?<>أكتر من <b>200</b> قطعة محتوى.<br/>مع <b>30+</b> براند وعميل.</>:<><b>200+</b> short-form pieces.<br/><b>30+</b> brands &amp; clients.</>}</h2><p>{rtl?"نجاحات، تجارب، ودروس شكّلت الخطوة اللي بعدها.":"Wins, misses, tests—and the thinking behind the next move."}</p></div><div className="motionRows" dir="ltr">{proofRows.map((row,rowIndex)=><div className={`motionViewport row-${rowIndex+1}`} key={rowIndex}><div className="motionTrack">{[0,1].map(copy=><div className="motionGroup" aria-hidden={copy===1} key={copy}>{row.map((item,i)=><a href={item.href} target="_blank" rel="noreferrer" className="proofTile" key={`${copy}-${i}`} aria-label={item.alt} tabIndex={copy===1?-1:undefined}><img src={item.image} alt={copy===0?item.alt:""}/><span>↗</span></a>)}</div>)}</div></div>)}</div><a className="proofWallCta" href="#rabha-case">{rtl?"استكشف تفاصيل المشاريع":"EXPLORE THE CASE STUDIES"}<span>↓</span></a></section>
    <section className="rabhaCase" id="rabha-case">
      <div className="sectionIndex light">03 / FEATURED CASE STUDY</div>
      <div className="rabhaIntro"><div><p>{rtl?"رابحة · مصنع عبايات للتجار والموزعين":"RABHA · B2B ABAYA MANUFACTURER"}</p><h2>{rtl?"من صفر متابع إلى مليون جنيه مبيعات.":"From zero followers to EGP 1M in sales."}</h2></div><span>{rtl?"شهران · بدون إعلانات ممولة":"TWO MONTHS · ZERO PAID ADS"}</span></div>
      <div className="rabhaStats"><article><b>41</b><span>{rtl?"فيديو خلال شهرين":"VIDEOS IN TWO MONTHS"}</span></article><article><b>47K</b><span>{rtl?"مشاهدة لأقوى فيديو":"TOP VIDEO VIEWS"}</span></article><article><b>2.2K</b><span>{rtl?"متابع من نقطة بداية صفر":"FOLLOWERS FROM ZERO"}</span></article><article className="wineStat"><b>1M</b><span>{rtl?"جنيه مبيعات في الشهر الثاني":"EGP SALES IN MONTH TWO"}</span></article></div>
      <div className="caseStory">
        <article><small>01 / {rtl?"التحدي":"CHALLENGE"}</small><h3>{rtl?"عملاء أورجانيك، بدون ميزانية إعلانات.":"Organic leads, without an ad budget."}</h3><p>{rtl?"كان هدف صاحب المصنع الوصول إلى التجار والموزعين وتحويل المحتوى إلى استفسارات ومبيعات، بينما بدأت الصفحة من صفر متابع.":"The factory needed to reach traders and distributors and turn content into inquiries and sales, starting from an account with zero followers."}</p></article>
        <article><small>02 / {rtl?"الاستراتيجية":"STRATEGY"}</small><h3>{rtl?"Funnel يتطور مع استجابة السوق.":"A funnel shaped by market response."}</h3><p>{rtl?"حددت الجمهور ومشكلاته، وبنيت مسارًا بدأ بالوعي ثم الثقة ثم البيع. اختبرت فورمات مختلفة وطورتها حسب ما جذب العملاء، واقترحت عرض البدء بكميات صغيرة لتقليل مخاطرة التاجر.":"I defined the audience and its problems, then built a funnel from awareness to trust to sales. Formats evolved with response, alongside a small-quantity offer designed to reduce the trader’s risk."}</p></article>
        <article><small>03 / {rtl?"دوري":"MY ROLE"}</small><h3>{rtl?"استراتيجية، كتابة، اتجاه محتوى، وتصوير بسيط.":"Strategy, writing, content direction, and simple shooting."}</h3><p>{rtl?"بنيت استراتيجية المحتوى والأفكار والفورمات، كتبت السكريبتات، حددت طريقة التنفيذ، وضبطت الإضاءة والكادر وصورت المحتوى. نفذ المونتاج محرر فيديو، ونفذ الهوية مصمم براندينج.":"I built the content strategy, formats, ideas and scripts, set the execution direction, and handled the lighting, framing and shooting. Editing and brand design were delivered by specialist collaborators."}</p></article>
      </div>
      <div className="reelShowcase"><div className="reelShowcaseHead"><p>{rtl?"أفضل الفيديوهات أداءً":"TOP-PERFORMING VIDEOS"}</p><span>{rtl?"اضغط على أي صورة لمشاهدة الفيديو على فيسبوك":"SELECT A COVER TO WATCH ON FACEBOOK"}</span></div><div className="reelGrid">{rabhaReels.map((reel,i)=><a href={`https://www.facebook.com/reel/${reel.id}/`} target="_blank" rel="noreferrer" key={reel.id} className="reelCard"><img src={reel.image} alt={rtl?`غلاف فيديو رابحة بعدد ${reel.views} مشاهدة`:`Rabha reel cover with ${reel.views} views`}/><div><small>0{i+1}</small><b>{reel.views}</b><span>{rtl?"مشاهدة":"VIEWS"}</span><i>↗</i></div></a>)}</div></div>
      <div className="formatStrip"><p>{rtl?"الفورمات التي تم اختبارها":"FORMATS TESTED"}</p>{(rtl?["مشكلة وحل","داخل المصنع","مراحل التصنيع","عرض بيعي","تفاصيل المنتج","رسائل ثقة"]:["Problem / solution","Inside the factory","Making process","Sales offer","Product detail","Trust building"]).map(x=><span key={x}>{x}</span>)}</div>
      <a className="rabhaLink" href="https://www.facebook.com/people/Rabha/61588290807233/?sk=reels_tab" target="_blank" rel="noreferrer">{rtl?"شاهد الـ41 فيديو على فيسبوك":"VIEW ALL 41 VIDEOS ON FACEBOOK"}<span>↗</span></a>
    </section>
    <section className="mariemCase" id="mariem-case">
      <div className="sectionIndex">04 / FEATURED CASE STUDY</div>
      <div className="mariemIntro"><div><p>{rtl?"مريم حجاب · براند أزياء نسائية":"MARIEM HIJAB · WOMEN’S FASHION BRAND"}</p><h2>{rtl?"قصة واحدة حققت هدف الشهر في أسبوعين.":"One story hit the monthly goal in two weeks."}</h2></div><span>{rtl?"4 شهور · محتوى أورجانيك وإعلاني":"4 MONTHS · ORGANIC & PAID CONTENT"}</span></div>
      <div className="mariemGrowth"><div><small>{rtl?"نقطة البداية":"START"}</small><b>174K</b><span>{rtl?"متابع تقريبًا":"APPROX. FOLLOWERS"}</span></div><i>→</i><div className="growthResult"><small>{rtl?"هدف الشهر":"MONTHLY GOAL"}</small><b>200K</b><span>{rtl?"تم الوصول إليه في الأسبوع الثاني":"REACHED IN WEEK TWO"}</span></div><article><b>2M</b><span>{rtl?"مشاهدة أورجانيك · بدون إعلانات":"ORGANIC VIEWS · NO PAID SUPPORT"}</span></article></div>
      <div className="mariemStory">
        <article><small>01 / {rtl?"المهمة":"THE BRIEF"}</small><h3>{rtl?"تحويل الاستراتيجية إلى محتوى يتحرك.":"Turn strategy into content that moves."}</h3><p>{rtl?"استلمت استراتيجية الماركتنج والـJobs To Be Done من المانجر، ثم حللت مشكلات المحتوى، استخرجت الـUSP، وحولتها إلى خطة فورمات وسكريبتات قابلة للاختبار.":"I received the marketing strategy and Jobs To Be Done from the manager, then diagnosed content problems, surfaced the USP, and translated both into testable formats and scripts."}</p></article>
        <article className="storyCard"><small>02 / {rtl?"الفيديو الرئيسي":"THE BREAKOUT REEL"}</small><h3>{rtl?"هوك درامي + سؤال رقمي مفتوح.":"Drama hook + numerical open loop."}</h3><p>{rtl?"بدأ الفيديو بحركة وموقف تمثيلي بدل تقديم مباشر، ثم فتح سؤال: «170 قطعة في أوردر واحد… إيه الحكاية؟». القصة عرضت حجم البراند وثقة العملاء بدون أي بيع مباشر.":"The reel opened inside an acted moment instead of a presenter intro, then asked: ‘170 pieces in one order—what’s the story?’ It demonstrated scale and trust without a direct sales pitch."}</p></article>
        <article><small>03 / {rtl?"دوري والتعاون":"ROLE & COLLABORATION"}</small><h3>{rtl?"كتابة كل المحتوى وتوجيه التنفيذ.":"Writing every script and guiding execution."}</h3><p>{rtl?"كنت المسؤول الوحيد عن كتابة محتوى البراند خلال الأربعة شهور، وطورت الفورمات وزوايا الإعلانات، وصورت فيديوهات مختارة. نفذ فريق الشركة التصوير والمونتاج في باقي المحتوى وفق التوجيه والسكريبتات.":"I was the brand’s sole content writer during the four months, developed formats and ad angles, and shot selected videos. The company’s creative team filmed and edited the remaining work from my scripts and content direction."}</p></article>
      </div>
      <div className="salesRun"><div className="salesRunHead"><p>{rtl?"إجمالي مبيعات البراند أثناء فترة إدارة المحتوى":"TOTAL BRAND SALES DURING THE CONTENT TENURE"}</p><b>≈ 1.57M EGP</b></div><div className="salesBars">{[{m:"M1",v:"70K",h:"12%"},{m:"M2",v:"400K",h:"67%"},{m:"M3",v:"600K",h:"100%"},{m:"M4",v:"500K",h:"83%"}].map(x=><article key={x.m}><div><span style={{height:x.h}} /></div><small>{x.m}</small><b>{x.v}</b></article>)}</div><p className="salesNote">{rtl?"هذه أرقام إجمالي مبيعات البراند وليست مبيعات منسوبة للمحتوى وحده. ساهم المحتوى ضمن منظومة شملت المنتج والميديا باير وفريق التنفيذ.":"These are total brand sales, not sales attributed to content alone. Content contributed within a wider system including product, media buying, and the production team."}</p></div>
      <div className="mariemReels"><div className="reelShowcaseHead"><p>{rtl?"من القصة إلى الإعلان":"FROM STORY TO PERFORMANCE CREATIVE"}</p><span>{rtl?"اضغط على أي صورة لمشاهدة الفيديو":"SELECT A COVER TO WATCH THE REEL"}</span></div><div className="reelGrid">{mariemReels.map((reel,i)=><a href={`https://www.facebook.com/reel/${reel.id}/`} target="_blank" rel="noreferrer" key={reel.id} className="reelCard mariemReel"><img src={reel.image} alt={rtl?`غلاف فيديو مريم حجاب ${reel.views}`:`Mariem Hijab reel cover ${reel.views}`}/><div><small>0{i+1}</small><b>{reel.views}</b><span>{rtl?reel.ar:reel.en}</span><i>↗</i></div></a>)}</div></div>
      <a className="mariemLink" href="https://www.facebook.com/profile.php?id=100078683716290&sk=reels_tab" target="_blank" rel="noreferrer">{rtl?"شاهد صفحة مريم حجاب":"VIEW MARIEM HIJAB ON FACEBOOK"}<span>↗</span></a>
    </section>
    <section className="morehCase" id="moreh-case">
      <div className="sectionIndex light">05 / FEATURED CASE STUDY</div>
      <div className="morehIntro"><div><p>{rtl?"مريح · ملابس طبية":"MOREH · MEDICAL WEAR"}</p><h2>{rtl?"من طلب عاجل إلى عائد 11× خلال 10 أيام.":"From an urgent brief to 11× return in 10 days."}</h2></div><span>{rtl?"شهر واحد · كريتيفز DARK ADS":"ONE MONTH · DARK ADS CREATIVES"}</span></div>
      <div className="morehStats"><article><b>77K</b><span>{rtl?"جنيه مبيعات":"EGP SALES"}</span></article><article><b>7K</b><span>{rtl?"جنيه إنفاق إعلاني":"EGP AD SPEND"}</span></article><article className="morehAccent"><b>≈11×</b><span>{rtl?"عائد على الإنفاق":"RETURN ON AD SPEND"}</span></article><article><b>10</b><span>{rtl?"أيام للنتيجة":"DAYS TO RESULT"}</span></article></div>
      <p className="morehSource">{rtl?"أرقام أول 10 أيام وفقًا لتقرير الميديا باير.":"First 10-day figures reported by the media buyer."}</p>
      <div className="morehStory">
        <article><small>01 / {rtl?"التحدي":"CHALLENGE"}</small><h3>{rtl?"الأونر كان محتاج مبيعات بسرعة.":"The owner needed revenue fast."}</h3><p>{rtl?"بدل انتظار بناء مسار أورجانيك طويل، كان المطلوب تجهيز كريتيفز بيع مباشرة وإطلاقها كـDark Ads في وقت قصير.":"Instead of waiting for a long organic runway, the brief was to create direct-response videos that could launch quickly as dark ads."}</p></article>
        <article className="morehStoryAccent"><small>02 / {rtl?"المسار الإبداعي":"CREATIVE ROUTE"}</small><h3>{rtl?"مشكلات يوم العمل تحولت إلى زوايا بيع.":"Long-shift problems became sales angles."}</h3><p>{rtl?"ركزت الكريتيفز على الراحة، حرية الحركة، ملاءمة الحجاب، الشيفت الطويل وتفاصيل المنتج؛ بفورمات قصيرة تقود المشاهد من المشكلة إلى المنتج مباشرة.":"The creatives focused on comfort, movement, modest fit, long shifts, and product details—moving quickly from a real workday problem to the product."}</p></article>
        <article><small>03 / {rtl?"دوري والتعاون":"ROLE & COLLABORATION"}</small><h3>{rtl?"فكرة، زاوية، كتابة وتصوير.":"Concept, angle, writing, and shooting."}</h3><p>{rtl?"جهزت أفكار الحملة وزوايا البيع والسكريبتات، ثم صورت الكريتيفز. نفّذ فريق المونتاج في الشركة مرحلة ما بعد الإنتاج، وأدار الميديا باير إطلاق الإعلانات وقياس النتائج.":"I developed the campaign concepts, sales angles, and scripts, then shot the creatives. The in-house editing team handled post-production, while the media buyer launched and measured the ads."}</p></article>
      </div>
      <div className="morehEvidence"><figure><img src="/moreh/results.png" alt={rtl?"لقطة من نتائج حملة مريح":"Moreh campaign results dashboard"}/></figure><div><small>{rtl?"لقطة أداء إضافية":"ADDITIONAL PERFORMANCE SNAPSHOT"}</small><h3>7.56× ROAS</h3><ul><li><b>27</b>{rtl?" عملية شراء":" purchases"}</li><li><b>139.57 EGP</b>{rtl?" تكلفة الشراء":" cost per purchase"}</li><li><b>5.14%</b> CTR</li><li><b>24,469</b>{rtl?" وصول":" reach"}</li></ul><p>{rtl?"هذه اللقطة تعرض نطاقًا مختلفًا أو جزءًا من الحملة عن ملخص أول 10 أيام؛ لذلك تُعرض كدليل أداء منفصل.":"This dashboard covers a different range or subset from the first 10-day summary, so it is shown as separate supporting evidence."}</p></div></div>
      <div className="morehCreatives"><div className="reelShowcaseHead"><p>{rtl?"كريتيفز الحملة":"CAMPAIGN CREATIVES"}</p><span>{rtl?"عينات مختارة من الفيديوهات التي تم تنفيذها":"SELECTED EXECUTED VIDEO SAMPLES"}</span></div><div className="morehCreativeGrid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))",maxWidth:820}}>
        <a href="https://www.instagram.com/p/DV3oF1xtDp5/?hl=en" target="_blank" rel="noreferrer"><img src="/moreh/creative-hijabi.jpg" alt={rtl?"كريتيف مريح للمحجبات":"Moreh modest-fit creative"}/><div><small>01</small><b>{rtl?"ملاءمة الحجاب":"MODEST-FIT PROBLEM / SOLUTION"}</b><i>↗</i></div></a>
        <a href="https://www.instagram.com/p/DVGa61jDeK4/?hl=en" target="_blank" rel="noreferrer"><img src="/moreh/creative-shift.jpg" alt={rtl?"كريتيف مريح للشيفت الطويل":"Moreh long-shift creative"}/><div><small>02</small><b>{rtl?"راحة الشيفت الطويل":"LONG-SHIFT BENEFIT ANGLE"}</b><i>↗</i></div></a>
      </div></div>
      <div className="approvedConcept"><small>{rtl?"اتجاه أورجانيك معتمد · لم يُنتج":"APPROVED ORGANIC DIRECTION · UNPRODUCED"}</small><div><h3>{rtl?"صوت قماش بيتقطع… ده حال دكاترة العلاج الطبيعي.":"Fabric tears. That’s a physiotherapist’s scrub problem."}</h3><p>{rtl?"سكريبت تمثيلي يبدأ بـAudio Pattern Interrupt، ثم يحول مشكلة حركة حقيقية إلى حل منتج واضح: بنطلون بقصة أوسع، حركة أريح، وضمان سنتين. تمت الموافقة على الفكرة والسكريبت، لكن لم تُنتج بسبب عدم توفر الميزانية.":"A scripted social concept opening with an audio pattern interrupt, then turning a real movement problem into a clear product solution: a wider cut, easier movement, and a two-year guarantee. The direction and script were approved but not produced because budget was unavailable."}</p></div></div>
      <a className="morehLink" href="https://www.instagram.com/morehmedwear/?hl=en" target="_blank" rel="noreferrer">{rtl?"شاهد مريح على إنستجرام":"VIEW MOREH ON INSTAGRAM"}<span>↗</span></a>
    </section>
    <section className="approachSection" id="approach"><div className="sectionIndex light">06 / PROCESS</div><div className="approachTop"><p>{t.approachK}</p><h2>{t.approachTitle}</h2><span>{t.approachIntro}</span></div><figure className="processPhoto"><img src="/abdallah-process.jpg" alt={rtl?"كواليس تجهيز موقع تصوير":"Behind the scenes of a production setup"}/><figcaption>BEHIND THE SCENES · DIRECTION IN PRACTICE</figcaption></figure><div className="steps">{t.steps.map(s=><article key={s[0]}><b>{s[0]}</b><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}</div></section>
    <section className="aboutSection" id="about"><div className="sectionIndex">07 / PROFILE</div><div className="aboutGrid"><figure className="portraitType"><img src="/abdallah-about.jpg" alt={rtl?"صورة عبدالله المهندس":"Portrait of Abdallah Al-Mohandes"}/><span>ABDALLAH</span><i>AL-MOHANDES</i></figure><div className="aboutText"><small>{t.aboutK}</small><h2>{t.aboutTitle}</h2><p>{t.aboutP}</p><div className="abilities">{t.abilities.map((a,i)=><span key={a}><b>0{i+1}</b>{a}</span>)}</div></div></div></section>
    <section className="finalCta"><p>{t.ctaK}</p><h2>{t.ctaTitle}</h2><a href="mailto:abdallamhmd273@gmail.com">{t.email}<span>↗</span></a></section>
    <footer><a className="wordmark" href="#top">HANDASA<span>®</span></a><p>{t.footer}</p><div><a href="https://www.instagram.com/handasa.com_/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/in/abdallah-al-mohandes-8b5698371/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></footer>
  </main>
}
