"use client";
import { useState } from "react";

type Lang = "en" | "ar";
type Filter = "all" | "reach" | "direction" | "sales" | "leads";

const ui = {
  en: {
    nav: [["#approach","Approach"],["#work","Selected work"],["#about","About"]], available:"Open to the right opportunity", role:"Creative & Content Strategist", leadA:"Strategy behind", leadB:"content that moves.", intro:"I turn scattered content into a clear strategy, sharper ideas, and work that earns attention — then moves people to act.", work:"Explore the work", contact:"Let’s talk", proof:"Proof, matched to the problem", metrics:["Organic reach","Zero ad spend","One video"], choose:"What needs to move?", chooseSub:"Start with the business problem. I’ll show you the work that answers it.", filters:{all:"All work",reach:"Reach",direction:"Direction",sales:"Sales",leads:"Lead generation"}, cases:"Selected evidence", open:"View project", approachK:"The approach", approachTitle:"Creative, but never random.", approachIntro:"Every piece of content gets a job before it gets a format.", steps:[["01","Find the real problem","I begin with the goal, audience, funnel stage, and the one action content needs to drive."],["02","Build the route","I turn insights into pillars, hooks, scripts, visual direction, and a clear production path."],["03","Test what works","I align the team, ship, read performance, and iterate until the result speaks."]], aboutK:"Profile", aboutTitle:"The strategist who can execute.", aboutP:"I work between strategy and the people bringing it to life — connecting content, copy, design, video, media buying, and the client around one clear direction.", abilities:["Content Strategy","Creative Ideation","Creative Direction","Performance Copy","Organic Testing","Cross-team Execution"], ctaK:"Have a content problem?", ctaTitle:"Let’s make the next move clear.", email:"Start a conversation", footer:"Abdallah Al-Mohandes — Cairo, Egypt"
  },
  ar: {
    nav: [["#approach","طريقتي"],["#work","أعمال مختارة"],["#about","عني"]], available:"متاح للفرصة المناسبة", role:"استراتيجي إبداع ومحتوى", leadA:"استراتيجية وراء", leadB:"محتوى يصنع تأثيرًا.", intro:"أحوّل المحتوى المتفرق إلى استراتيجية واضحة، وأفكار أقوى، وتنفيذ يجذب الانتباه — ثم يدفع الناس لاتخاذ خطوة.", work:"شاهد الأعمال", contact:"تواصل معي", proof:"الدليل المناسب لكل مشكلة", metrics:["وصول طبيعي","بدون إعلانات","فيديو واحد"], choose:"إيه اللي محتاج يتحرك؟", chooseSub:"نبدأ من مشكلة البزنس، وبعدها تشوف الشغل اللي يثبت قدرتي على حلها.", filters:{all:"كل الأعمال",reach:"الانتشار",direction:"الاتجاه الإبداعي",sales:"المبيعات",leads:"العملاء المحتملون"}, cases:"أدلة من الشغل", open:"شاهد المشروع", approachK:"طريقة الشغل", approachTitle:"إبداع، لكن مش عشوائي.", approachIntro:"كل قطعة محتوى لازم يكون لها دور قبل ما يكون لها شكل.", steps:[["01","نحدد المشكلة الحقيقية","أبدأ بالهدف والجمهور ومرحلة الـfunnel والخطوة الواحدة المطلوبة من المحتوى."],["02","نبني الطريق","أحوّل الفهم إلى محاور وhooks وسكريبتات واتجاه بصري ومسار تنفيذ واضح."],["03","نختبر اللي بيشتغل","أوحّد الفريق، ننشر، نقرأ الأداء ونطوّر لحد ما النتيجة تتكلم."]], aboutK:"عنّي", aboutTitle:"استراتيجي يعرف ينفّذ.", aboutP:"أعمل في المساحة بين الاستراتيجية والأشخاص الذين يحولونها إلى واقع — أوحّد المحتوى والكتابة والتصميم والفيديو والميديا باينج والعميل حول اتجاه واحد واضح.", abilities:["استراتيجية المحتوى","ابتكار الأفكار","التوجيه الإبداعي","كتابة إعلانات الأداء","الاختبار الطبيعي","تنسيق الفرق"], ctaK:"عندك مشكلة في المحتوى؟", ctaTitle:"خلّينا نخلي الخطوة الجاية واضحة.", email:"ابدأ محادثة", footer:"عبدالله المهندس — القاهرة، مصر"
  }
};

const caseStudies = [
  {id:"emanly", cat:["reach","sales"], num:"2.4M", en:{name:"Emanly Handmade", label:"Organic growth · Sales", desc:"From no video crossing 10K to organic sales in two weeks — with zero ad spend."}, ar:{name:"Emanly Handmade", label:"انتشار طبيعي · مبيعات", desc:"من عدم تخطي 10 آلاف مشاهدة إلى مبيعات طبيعية خلال أسبوعين — بدون إنفاق إعلاني."}, href:"https://www.tiktok.com/@emanly_handmade"},
  {id:"mariem", cat:["reach"], num:"1M", en:{name:"Mariem Hijab", label:"Organic reach", desc:"Reversed declining reach by testing formats and rebuilding hooks around audience behavior."}, ar:{name:"Mariem Hijab", label:"وصول طبيعي", desc:"حوّلنا تراجع الوصول باختبار أشكال جديدة وإعادة بناء الـhooks حول سلوك الجمهور."}, href:"https://www.facebook.com/share/1F3Zv3PH4H/"},
  {id:"tallah", cat:["direction"], num:"NEW", en:{name:"Tallah Dental", label:"Creative direction", desc:"Rebuilt the on-camera identity and production setup using the same clinic and the same budget."}, ar:{name:"Tallah Dental", label:"توجيه إبداعي", desc:"أعدنا بناء الهوية أمام الكاميرا وتجهيز التصوير بنفس العيادة ونفس الميزانية."}, href:"https://www.instagram.com/reel/DO3vFeaDEXN/"},
  {id:"firstaxes", cat:["leads"], num:"LEADS", en:{name:"First Axes", label:"Funnel · Performance copy", desc:"Moved an empty startup account toward lead generation through market pain and awareness-first creative."}, ar:{name:"First Axes", label:"Funnel · كتابة أداء", desc:"حوّلنا حساب شركة ناشئة فارغ نحو توليد العملاء بفهم ألم السوق ومحتوى يبدأ بالوعي."}, href:"https://www.instagram.com/reel/DU3MdOqCPDs/"},
  {id:"tasawk", cat:["reach","leads"], num:"500↑", en:{name:"Tasawk", label:"Format testing · Funnel", desc:"Broke the organic view ceiling while driving webinar registrations to build a warm audience."}, ar:{name:"Tasawk", label:"اختبار أشكال · Funnel", desc:"كسرنا سقف المشاهدات الطبيعية مع جذب تسجيلات للويبنار وبناء جمهور دافئ."}, href:"https://www.instagram.com/tasawk.sa"},
  {id:"stech", cat:["leads"], num:"WA", en:{name:"STech", label:"Awareness · WhatsApp leads", desc:"Built product awareness and generated fast consultation leads through Spark and dark ads."}, ar:{name:"STech", label:"وعي · عملاء واتساب", desc:"بنينا الوعي بالمنتج وحققنا عملاء استشارات بسرعة باستخدام Spark وDark Ads."}, href:"https://www.instagram.com/p/DUXtm_UDCcF/"},
];

export default function Home(){
  const [lang,setLang]=useState<Lang>("en"); const [filter,setFilter]=useState<Filter>("all"); const t=ui[lang]; const rtl=lang==="ar";
  const visible=caseStudies.filter(c=>filter==="all"||c.cat.includes(filter));
  return <main className={rtl?"site rtl":"site"} dir={rtl?"rtl":"ltr"}>
    <nav className="newNav"><a href="#top" className="wordmark">HANDASA<span>®</span></a><div className="navCenter">{t.nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</div><div className="navActions"><button className="langSwitch" onClick={()=>setLang(rtl?"en":"ar")} aria-label={rtl?"Switch to English":"التبديل للعربية"}>{rtl?"EN":"ع"}</button><a className="contactPill" href="mailto:abdallamhmd273@gmail.com">{t.contact} <span>↗</span></a></div></nav>
    <section className="newHero" id="top"><div className="statusLine"><span className="statusDot" />{t.available}<b>CAIRO · EGYPT</b></div><p className="roleLabel">{t.role}</p><h1><span>{t.leadA}</span><strong>{t.leadB}</strong></h1><figure className="heroPortrait"><img src="/abdallah-hero.jpg" alt={rtl?"عبدالله أثناء إدارة تصوير محتوى":"Abdallah directing a content shoot"}/><figcaption><span>ON SET</span><b>01</b></figcaption></figure><div className="heroFooter"><p>{t.intro}</p><div className="heroCtas"><a href="#work" className="primaryCta">{t.work}<span>↓</span></a><a href="mailto:abdallamhmd273@gmail.com" className="textCta">{t.contact} ↗</a></div></div><div className="proofRail"><div className="proofTitle"><small>01 / RESULTS</small><p>{t.proof}</p></div><div className="metric"><b>1M+</b><span>{t.metrics[0]}</span></div><div className="metric accent"><b>0</b><span>{t.metrics[1]}</span></div><div className="metric"><b>2.4M</b><span>{t.metrics[2]}</span></div><div className="railArrow">↘</div></div></section>
    <section className="problemSection" id="work"><div className="sectionIndex">02 / WORK</div><div className="problemHeading"><h2>{t.choose}</h2><p>{t.chooseSub}</p></div><div className="filterBar">{(Object.keys(t.filters) as Filter[]).map(key=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{t.filters[key]}<span>{key==="all"?caseStudies.length:caseStudies.filter(c=>c.cat.includes(key)).length}</span></button>)}</div><div className="caseHeading"><p>{t.cases}</p><span>{String(visible.length).padStart(2,"0")} / {String(caseStudies.length).padStart(2,"0")}</span></div><div className="caseGrid">{visible.map((c,i)=>{const text=c[lang];return <a className="caseCard" href={c.href} target="_blank" rel="noreferrer" key={c.id}><div className={`caseVisual visual-${c.id}`}><span>0{i+1}</span><b>{c.num}</b><i>↗</i></div><div className="caseMeta"><small>{text.label}</small><h3>{text.name}</h3><p>{text.desc}</p><em>{t.open} ↗</em></div></a>})}</div></section>
    <section className="approachSection" id="approach"><div className="sectionIndex light">03 / PROCESS</div><div className="approachTop"><p>{t.approachK}</p><h2>{t.approachTitle}</h2><span>{t.approachIntro}</span></div><figure className="processPhoto"><img src="/abdallah-process.jpg" alt={rtl?"كواليس تجهيز موقع تصوير":"Behind the scenes of a production setup"}/><figcaption>BEHIND THE SCENES · DIRECTION IN PRACTICE</figcaption></figure><div className="steps">{t.steps.map(s=><article key={s[0]}><b>{s[0]}</b><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}</div></section>
    <section className="aboutSection" id="about"><div className="sectionIndex">04 / PROFILE</div><div className="aboutGrid"><figure className="portraitType"><img src="/abdallah-about.jpg" alt={rtl?"صورة عبدالله المهندس":"Portrait of Abdallah Al-Mohandes"}/><span>ABDALLAH</span><i>AL-MOHANDES</i></figure><div className="aboutText"><small>{t.aboutK}</small><h2>{t.aboutTitle}</h2><p>{t.aboutP}</p><div className="abilities">{t.abilities.map((a,i)=><span key={a}><b>0{i+1}</b>{a}</span>)}</div></div></div></section>
    <section className="finalCta"><p>{t.ctaK}</p><h2>{t.ctaTitle}</h2><a href="mailto:abdallamhmd273@gmail.com">{t.email}<span>↗</span></a></section>
    <footer><a className="wordmark" href="#top">HANDASA<span>®</span></a><p>{t.footer}</p><div><a href="https://www.instagram.com/handasa.com_/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/in/abdallah-al-mohandes-8b5698371/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></footer>
  </main>
}
