"use client";
import { useState } from "react";

type Lang = "en" | "ar";
type Filter = "all" | "reach" | "direction" | "sales" | "leads";

const ui = {
  en: {
    nav: [["#approach","Approach"],["#work","Selected work"],["#about","About"]], available:"Open to the right opportunity", role:"Creative & Content Strategist", leadA:"Strategy behind", leadB:"content that moves.", intro:"I turn scattered content into a clear strategy, sharper ideas, and work that earns attention — then moves people to act.", work:"Explore the work", contact:"Let’s talk", proof:"Proof, matched to the problem", metrics:["Organic reach","Zero ad spend","One video"], choose:"What needs to move?", chooseSub:"Start with the business problem. I’ll show you the work that answers it.", filters:{all:"All work",reach:"Reach",direction:"Direction",sales:"Sales",leads:"Lead generation"}, cases:"Selected evidence", open:"View project", approachK:"The approach", approachTitle:"Creative, but never random.", approachIntro:"Every piece of content gets a job before it gets a format.", steps:[["01","Find the real problem","I begin with the goal, audience, funnel stage, and the one action content needs to drive."],["02","Build the route","I turn insights into pillars, hooks, scripts, visual direction, and a clear production path."],["03","Test what works","I align the team, ship, read performance, and iterate until the result speaks."]], aboutK:"Profile", aboutTitle:"The strategist who can execute.", aboutP:"I work between strategy and the people bringing it to life — connecting content, copy, design, video, media buying, and the client around one clear direction.", abilities:["Content Strategy","Creative Ideation","Creative Direction","Performance Copy","Organic Testing","Cross-team Execution"], ctaK:"Have a content problem?", ctaTitle:"Let’s make the next move clear.", email:"Start a conversation", footer:"Abdallah Al-Mohandes — Cairo, Egypt"
  },
  ar: {
    nav: [["#approach","طريقتي"],["#work","أعمال مختارة"],["#about","عني"]], available:"متاح للفرصة المناسبة", role:"استراتيجي إبداع ومحتوى", leadA:"استراتيجية وراء", leadB:"محتوى يصنع تأثيرًا.", intro:"أحوّل المحتوى المتفرق إلى استراتيجية واضحة، وأفكار أقوى، وتنفيذ يجذب الانتباه — ثم يدفع الناس لاتخاذ خطوة.", work:"شاهد الأعمال", contact:"تواصل معي", proof:"الدليل المناسب لكل مشكلة", metrics:["وصول طبيعي","بدون إعلانات","فيديو واحد"], choose:"إيه اللي محتاج يتحرك؟", chooseSub:"نبدأ من مشكلة البزنس، وبعدها تشوف الشغل اللي يثبت قدرتي على حلها.", filters:{all:"كل الأعمال",reach:"الانتشار",direction:"الاتجاه الإبداعي",sales:"المبيعات",leads:"العملاء المحتملون"}, cases:"أدلة من الشغل", open:"شاهد المشروع", approachK:"طريقة الشغل", approachTitle:"إبداع، لكن مش عشوائي.", approachIntro:"كل قطعة محتوى لازم يكون لها دور قبل ما يكون لها شكل.", steps:[["01","نحدد المشكلة الحقيقية","أبدأ بالهدف والجمهور ومرحلة الـfunnel والخطوة الواحدة المطلوبة من المحتوى."],["02","نبني الطريق","أحوّل الفهم إلى محاور وhooks وسكريبتات واتجاه بصري ومسار تنفيذ واضح."],["03","نختبر اللي بيشتغل","أوحّد الفريق، ننشر، نقرأ الأداء ونطوّر لحد ما النتيجة تتكلم."]], aboutK:"عنّي", aboutTitle:"استراتيجي يعرف ينفّذ.", aboutP:"أعمل في المساحة بين الاستراتيجية والأشخاص الذين يحولونها إلى واقع — أوحّد المحتوى والكتابة والتصميم والفيديو والميديا باينج والعميل حول اتجاه واحد واضح.", abilities:["استراتيجية المحتوى","ابتكار الأفكار","التوجيه الإبداعي","كتابة إعلانات الأداء","الاختبار الطبيعي","تنسيق الفرق"], ctaK:"عندك مشكلة في المحتوى؟", ctaTitle:"خلّينا نخلي الخطوة الجاية واضحة.", email:"ابدأ محادثة", footer:"عبدالله المهندس — القاهرة، مصر"
  }
};

const caseStudies = [
  {id:"rabha", cat:["reach","sales","leads"], num:"1M", en:{name:"Rabha", label:"Organic funnel · Sales", desc:"Built an organic content funnel from zero followers to EGP 1M in sales in month two — with no paid ads."}, ar:{name:"رابحة", label:"Funnel أورجانيك · مبيعات", desc:"بنيت منظومة محتوى من صفر متابع حتى مليون جنيه مبيعات في الشهر الثاني — بدون إعلانات ممولة."}, href:"#rabha-case"},
  {id:"emanly", cat:["reach","sales"], num:"2.4M", en:{name:"Emanly Handmade", label:"Organic growth · Sales", desc:"From no video crossing 10K to organic sales in two weeks — with zero ad spend."}, ar:{name:"Emanly Handmade", label:"انتشار طبيعي · مبيعات", desc:"من عدم تخطي 10 آلاف مشاهدة إلى مبيعات طبيعية خلال أسبوعين — بدون إنفاق إعلاني."}, href:"https://www.tiktok.com/@emanly_handmade"},
  {id:"mariem", cat:["reach","sales"], num:"2M", en:{name:"Mariem Hijab", label:"Story-led growth · Paid creative", desc:"One organic story-led reel took the page from about 174K to its 200K follower goal in the second week."}, ar:{name:"مريم حجاب", label:"نمو بالسرد القصصي · إعلانات", desc:"فيديو قصصي أورجانيك نقل الصفحة من نحو 174 ألف إلى هدف 200 ألف متابع في الأسبوع الثاني."}, href:"#mariem-case"},
  {id:"tallah", cat:["direction"], num:"NEW", en:{name:"Tallah Dental", label:"Creative direction", desc:"Rebuilt the on-camera identity and production setup using the same clinic and the same budget."}, ar:{name:"Tallah Dental", label:"توجيه إبداعي", desc:"أعدنا بناء الهوية أمام الكاميرا وتجهيز التصوير بنفس العيادة ونفس الميزانية."}, href:"https://www.instagram.com/reel/DO3vFeaDEXN/"},
  {id:"firstaxes", cat:["leads"], num:"LEADS", en:{name:"First Axes", label:"Funnel · Performance copy", desc:"Moved an empty startup account toward lead generation through market pain and awareness-first creative."}, ar:{name:"First Axes", label:"Funnel · كتابة أداء", desc:"حوّلنا حساب شركة ناشئة فارغ نحو توليد العملاء بفهم ألم السوق ومحتوى يبدأ بالوعي."}, href:"https://www.instagram.com/reel/DU3MdOqCPDs/"},
  {id:"tasawk", cat:["reach","leads"], num:"500↑", en:{name:"Tasawk", label:"Format testing · Funnel", desc:"Broke the organic view ceiling while driving webinar registrations to build a warm audience."}, ar:{name:"Tasawk", label:"اختبار أشكال · Funnel", desc:"كسرنا سقف المشاهدات الطبيعية مع جذب تسجيلات للويبنار وبناء جمهور دافئ."}, href:"https://www.instagram.com/tasawk.sa"},
  {id:"stech", cat:["leads"], num:"WA", en:{name:"STech", label:"Awareness · WhatsApp leads", desc:"Built product awareness and generated fast consultation leads through Spark and dark ads."}, ar:{name:"STech", label:"وعي · عملاء واتساب", desc:"بنينا الوعي بالمنتج وحققنا عملاء استشارات بسرعة باستخدام Spark وDark Ads."}, href:"https://www.instagram.com/p/DUXtm_UDCcF/"},
];

const rabhaReels = [
  {id:"2252826048836354", views:"47K", image:"/rabha/reel-47k.jpg"},
  {id:"921005460270732", views:"18K", image:"/rabha/reel-18k.jpg"},
  {id:"1487970329748086", views:"13K", image:"/rabha/reel-13k.jpg"},
  {id:"1342410861035210", views:"6.4K", image:"/rabha/reel-64k.jpg"},
  {id:"1517874099958400", views:"6K", image:"/rabha/reel-6k.jpg"},
  {id:"1306608900933541", views:"3.1K", image:"/rabha/reel-31k.jpg"},
];

const mariemReels = [
  {id:"852477507840942", views:"2M", image:"/mariem/reel-2m-new.jpg", en:"Organic storytelling", ar:"سرد قصصي أورجانيك"},
  {id:"1150334803884934", views:"155K", image:"/mariem/reel-155k.jpg", en:"Paid sales creative", ar:"محتوى بيعي للإعلانات"},
  {id:"4373980182748647", views:"149K", image:"/mariem/reel-149k.jpg", en:"Offer-led ad", ar:"عرض بيعي للإعلانات"},
  {id:"2127511864456822", views:"78K", image:"/mariem/reel-78k.jpg", en:"Ad script", ar:"سكريبت إعلاني"},
  {id:"1584204506002319", views:"60K", image:"/mariem/reel-60k.jpg", en:"Comfort angle", ar:"زاوية الراحة"},
  {id:"809876478729148", views:"42K", image:"/mariem/reel-42k.jpg", en:"Learning test", ar:"تجربة للتعلّم"},
];

export default function Home(){
  const [lang,setLang]=useState<Lang>("en"); const [filter,setFilter]=useState<Filter>("all"); const t=ui[lang]; const rtl=lang==="ar";
  const visible=caseStudies.filter(c=>filter==="all"||c.cat.includes(filter));
  return <main className={rtl?"site rtl":"site"} dir={rtl?"rtl":"ltr"}>
    <nav className="newNav"><a href="#top" className="wordmark">HANDASA<span>®</span></a><div className="navCenter">{t.nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</div><div className="navActions"><button className="langSwitch" onClick={()=>setLang(rtl?"en":"ar")} aria-label={rtl?"Switch to English":"التبديل للعربية"}>{rtl?"EN":"ع"}</button><a className="contactPill" href="mailto:abdallamhmd273@gmail.com">{t.contact} <span>↗</span></a></div></nav>
    <section className="newHero" id="top"><div className="statusLine"><span className="statusDot" />{t.available}<b>CAIRO · EGYPT</b></div><p className="roleLabel">{t.role}</p><h1><span>{t.leadA}</span><strong>{t.leadB}</strong></h1><figure className="heroPortrait"><img src="/abdallah-hero.jpg" alt={rtl?"عبدالله أثناء إدارة تصوير محتوى":"Abdallah directing a content shoot"}/><figcaption><span>ON SET</span><b>01</b></figcaption></figure><div className="heroFooter"><p>{t.intro}</p><div className="heroCtas"><a href="#work" className="primaryCta">{t.work}<span>↓</span></a><a href="mailto:abdallamhmd273@gmail.com" className="textCta">{t.contact} ↗</a></div></div><div className="proofRail"><div className="proofTitle"><small>01 / RESULTS</small><p>{t.proof}</p></div><div className="metric"><b>1M+</b><span>{t.metrics[0]}</span></div><div className="metric accent"><b>0</b><span>{t.metrics[1]}</span></div><div className="metric"><b>2.4M</b><span>{t.metrics[2]}</span></div><div className="railArrow">↘</div></div></section>
    <section className="problemSection" id="work"><div className="sectionIndex">02 / WORK</div><div className="problemHeading"><h2>{t.choose}</h2><p>{t.chooseSub}</p></div><div className="filterBar">{(Object.keys(t.filters) as Filter[]).map(key=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{t.filters[key]}<span>{key==="all"?caseStudies.length:caseStudies.filter(c=>c.cat.includes(key)).length}</span></button>)}</div><div className="caseHeading"><p>{t.cases}</p><span>{String(visible.length).padStart(2,"0")} / {String(caseStudies.length).padStart(2,"0")}</span></div><div className="caseGrid">{visible.map((c,i)=>{const text=c[lang];return <a className="caseCard" href={c.href} target="_blank" rel="noreferrer" key={c.id}><div className={`caseVisual visual-${c.id}`}><span>0{i+1}</span><b>{c.num}</b><i>↗</i></div><div className="caseMeta"><small>{text.label}</small><h3>{text.name}</h3><p>{text.desc}</p><em>{t.open} ↗</em></div></a>})}</div></section>
    <section className="rabhaCase" id="rabha-case">
      <div className="sectionIndex light">03 / FEATURED CASE STUDY</div>
      <div className="rabhaIntro"><div><p>{rtl?"رابحة · مصنع عبايات للتجار والموزعين":"RABHA · B2B ABAYA MANUFACTURER"}</p><h2>{rtl?"من صفر متابع إلى مليون جنيه مبيعات.":"From zero followers to EGP 1M in sales."}</h2></div><span>{rtl?"شهران · بدون إعلانات ممولة":"TWO MONTHS · ZERO PAID ADS"}</span></div>
      <div className="rabhaStats"><article><b>41</b><span>{rtl?"فيديو خلال شهرين":"VIDEOS IN TWO MONTHS"}</span></article><article><b>47K</b><span>{rtl?"مشاهدة لأقوى فيديو":"TOP VIDEO VIEWS"}</span></article><article><b>2.2K</b><span>{rtl?"متابع من نقطة بداية صفر":"FOLLOWERS FROM ZERO"}</span></article><article className="wineStat"><b>1M</b><span>{rtl?"جنيه مبيعات في الشهر الثاني":"EGP SALES IN MONTH TWO"}</span></article></div>
      <div className="caseStory">
        <article><small>01 / {rtl?"التحدي":"CHALLENGE"}</small><h3>{rtl?"عملاء أورجانيك، بدون ميزانية إعلانات.":"Organic leads, without an ad budget."}</h3><p>{rtl?"كان هدف صاحب المصنع الوصول إلى التجار والموزعين وتحويل المحتوى إلى استفسارات ومبيعات، بينما بدأت الصفحة من صفر متابع.":"The factory needed to reach traders and distributors and turn content into inquiries and sales, starting from an account with zero followers."}</p></article>
        <article><small>02 / {rtl?"الاستراتيجية":"STRATEGY"}</small><h3>{rtl?"Funnel يتطور مع استجابة السوق.":"A funnel shaped by market response."}</h3><p>{rtl?"حددت الجمهور ومشكلاته، وبنيت مسارًا بدأ بالوعي ثم الثقة ثم البيع. اختبرت فورمات مختلفة وطورتها حسب ما جذب العملاء، واقترحت عرض البدء بكميات صغيرة لتقليل مخاطرة التاجر.":"I defined the audience and its problems, then built a funnel from awareness to trust to sales. Formats evolved with response, alongside a small-quantity offer designed to reduce the trader’s risk."}</p></article>
        <article><small>03 / {rtl?"دوري":"MY ROLE"}</small><h3>{rtl?"استراتيجية، كتابة، اتجاه محتوى، وتصوير بسيط.":"Strategy, writing, content direction, and simple shooting."}</h3><p>{rtl?"بنيت استراتيجية المحتوى والأفكار والفورمات، كتبت السكريبتات، حددت طريقة التنفيذ، وضبطت الإضاءة والكادر وصورت المحتوى. نفذ المونتاج محرر فيديو، ونفذ الهوية مصمم براندينج.":"I built the content strategy, formats, ideas and scripts, set the execution direction, and handled the lighting, framing and shooting. Editing and brand design were delivered by specialist collaborators."}</p></article>
      </div>
      <div className="reelShowcase"><div className="reelShowcaseHead"><p>{rtl?"أفضل الفيديوهات أداءً":"TOP-PERFORMING VIDEOS"}</p><span>{rtl?"اضغط على أي صورة لمشاهدة الفيديو على فيسبوك":"SELECT A COVER TO WATCH ON FACEBOOK"}</span></div><div className="reelGrid">{rabhaReels.map((reel,i)=><a href={`https://www.facebook.com/reel/${reel.id}/`} target="_blank" rel="noreferrer" key={reel.id} className="reelCard"><img src={reel.image} alt={rtl?`غلاف فيديو رابحة بعدد ${reel.views} مشاهدة`:`Rabha reel cover with ${reel.views} views`}/><div><small>0{i+1}</small><b>{reel.views}</b><span>{rtl?"مشاهدة":"VIEWS"}</span><i>↗</i></div></a>)}</div></div>
      <div className="formatStrip"><p>{rtl?"الفورمات التي تم اختبارها":"FORMATS TESTED"}</p>{(rtl?["مشكلة وحل","داخل المصنع","مراحل التصنيع","عرض بيعي","تفاصيل المنتج","رسائل ثقة"]:["Problem / solution","Inside the factory","Making process","Sales offer","Product detail","Trust building"]).map(x=><span key={x}>{x}</span>)}</div>
      <a className="rabhaLink" href="https://www.facebook.com/people/Rabha/61588290807233/?sk=reels_tab" target="_blank" rel="noreferrer">{rtl?"شاهد الـ41 فيديو على فيسبوك":"VIEW ALL 41 VIDEOS ON FACEBOOK"}<span>↗</span></a>
    </section>
    <section className="mariemCase" id="mariem-case">
      <div className="sectionIndex">04 / FEATURED CASE STUDY</div>
      <div className="mariemIntro"><div><p>{rtl?"مريم حجاب · براند أزياء نسائية":"MARIEM HIJAB · WOMEN’S FASHION BRAND"}</p><h2>{rtl?"قصة واحدة حققت هدف الشهر في أسبوعين.":"One story hit the monthly goal in two weeks."}</h2></div><span>{rtl?"4 شهور · محتوى أورجانيك وإعلاني":"4 MONTHS · ORGANIC & PAID CONTENT"}</span></div>
      <div className="mariemGrowth"><div><small>{rtl?"نقطة البداية":"START"}</small><b>174K</b><span>{rtl?"متابع تقريبًا":"APPROX. FOLLOWERS"}</span></div><i>→</i><div className="growthResult"><small>{rtl?"هدف الشهر":"MONTHLY GOAL"}</small><b>200K</b><span>{rtl?"تم الوصول إليه في الأسبوع الثاني":"REACHED IN WEEK TWO"}</span></div><article><b>2M</b><span>{rtl?"مشاهدة أورجانيك · بدون إعلانات":"ORGANIC VIEWS · NO PAID SUPPORT"}</span></article></div>
      <div className="mariemStory">
        <article><small>01 / {rtl?"المهمة":"THE BRIEF"}</small><h3>{rtl?"تحويل الاستراتيجية إلى محتوى يتحرك.":"Turn strategy into content that moves."}</h3><p>{rtl?"استلمت استراتيجية الماركتنج والـJobs To Be Done من المانجر، ثم حللت مشكلات المحتوى، استخرجت الـUSP، وحولتها إلى خطة فورمات وسكريبتات قابلة للاختبار.":"I received the marketing strategy and Jobs To Be Done from the manager, then diagnosed content problems, surfaced the USP, and translated both into testable formats and scripts."}</p></article>
        <article className="storyCard"><small>02 / {rtl?"الفيديو الرئيسي":"THE BREAKOUT REEL"}</small><h3>{rtl?"هوك درامي + سؤال رقمي مفتوح.":"Drama hook + numerical open loop."}</h3><p>{rtl?"بدأ الفيديو بحركة وموقف تمثيلي بدل تقديم مباشر، ثم فتح سؤال: «170 قطعة في أوردر واحد… إيه الحكاية؟». القصة عرضت حجم البراند وثقة العملاء بدون أي بيع مباشر.":"The reel opened inside an acted moment instead of a presenter intro, then asked: ‘170 pieces in one order—what’s the story?’ It demonstrated scale and trust without a direct sales pitch."}</p></article>
        <article><small>03 / {rtl?"دوري والتعاون":"ROLE & COLLABORATION"}</small><h3>{rtl?"كتابة كل المحتوى وتوجيه التنفيذ.":"Writing every script and guiding execution."}</h3><p>{rtl?"كنت المسؤول الوحيد عن كتابة محتوى البراند خلال الأربعة شهور، وطورت الفورمات وزوايا الإعلانات، وصورت فيديوهات مختارة. نفذ فريق الشركة التصوير والمونتاج في باقي المحتوى وفق التوجيه والسكريبتات.":"I was the brand’s sole content writer during the four months, developed formats and ad angles, and shot selected videos. The company’s creative team filmed and edited the remaining work from my scripts and content direction."}</p></article>
      </div>
      <div className="salesRun"><div className="salesRunHead"><p>{rtl?"إجمالي مبيعات البراند أثناء فترة إدارة المحتوى":"TOTAL BRAND SALES DURING THE CONTENT TENURE"}</p><b>≈ 1.57M EGP</b></div><div className="salesBars">{[{m:"M1",v:"70K",h:"12%"},{m:"M2",v:"400K",h:"67%"},{m:"M3",v:"600K",h:"100%"},{m:"M4",v:"500K",h:"83%"}].map(x=><article key={x.m}><div><span style={{height:x.h}} /></div><small>{x.m}</small><b>{x.v}</b></article>)}</div><p className="salesNote">{rtl?"هذه أرقام إجمالي مبيعات البراند وليست مبيعات منسوبة للمحتوى وحده. ساهم المحتوى ضمن منظومة شملت المنتج والميديا باير وفريق التنفيذ.":"These are total brand sales, not sales attributed to content alone. Content contributed within a wider system including product, media buying, and the production team."}</p></div>
      <div className="mariemReels"><div className="reelShowcaseHead"><p>{rtl?"من القصة إلى الإعلان":"FROM STORY TO PERFORMANCE CREATIVE"}</p><span>{rtl?"اضغط على أي صورة لمشاهدة الفيديو":"SELECT A COVER TO WATCH THE REEL"}</span></div><div className="reelGrid">{mariemReels.map((reel,i)=><a href={`https://www.facebook.com/reel/${reel.id}/`} target="_blank" rel="noreferrer" key={reel.id} className="reelCard mariemReel"><img src={reel.image} alt={rtl?`غلاف فيديو مريم حجاب ${reel.views}`:`Mariem Hijab reel cover ${reel.views}`}/><div><small>0{i+1}</small><b>{reel.views}</b><span>{rtl?reel.ar:reel.en}</span><i>↗</i></div></a>)}</div></div>
      <a className="mariemLink" href="https://www.facebook.com/profile.php?id=100078683716290&sk=reels_tab" target="_blank" rel="noreferrer">{rtl?"شاهد صفحة مريم حجاب":"VIEW MARIEM HIJAB ON FACEBOOK"}<span>↗</span></a>
    </section>
    <section className="approachSection" id="approach"><div className="sectionIndex light">05 / PROCESS</div><div className="approachTop"><p>{t.approachK}</p><h2>{t.approachTitle}</h2><span>{t.approachIntro}</span></div><figure className="processPhoto"><img src="/abdallah-process.jpg" alt={rtl?"كواليس تجهيز موقع تصوير":"Behind the scenes of a production setup"}/><figcaption>BEHIND THE SCENES · DIRECTION IN PRACTICE</figcaption></figure><div className="steps">{t.steps.map(s=><article key={s[0]}><b>{s[0]}</b><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}</div></section>
    <section className="aboutSection" id="about"><div className="sectionIndex">04 / PROFILE</div><div className="aboutGrid"><figure className="portraitType"><img src="/abdallah-about.jpg" alt={rtl?"صورة عبدالله المهندس":"Portrait of Abdallah Al-Mohandes"}/><span>ABDALLAH</span><i>AL-MOHANDES</i></figure><div className="aboutText"><small>{t.aboutK}</small><h2>{t.aboutTitle}</h2><p>{t.aboutP}</p><div className="abilities">{t.abilities.map((a,i)=><span key={a}><b>0{i+1}</b>{a}</span>)}</div></div></div></section>
    <section className="finalCta"><p>{t.ctaK}</p><h2>{t.ctaTitle}</h2><a href="mailto:abdallamhmd273@gmail.com">{t.email}<span>↗</span></a></section>
    <footer><a className="wordmark" href="#top">HANDASA<span>®</span></a><p>{t.footer}</p><div><a href="https://www.instagram.com/handasa.com_/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/in/abdallah-al-mohandes-8b5698371/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></footer>
  </main>
}
